import Head from 'next/head'
import MainPageView from '../views'

export default function MainPage() {
  return (
    <>
      <Head>
        <title>Yany Choi's Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainPageView />
    </>
  )
}
