name: Github Pages Deployment
on:
  push:
    branches:
      - main


jobs:

  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.4]


    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Get Dependencies
      run: npm install

    - name: Build & Deploy to Github Pages
      run: npm run deploy